import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

import type { DiagnoseResponse, EngineResult } from "@/types"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export async function copyText(text: string) {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text)
    return
  }

  const textarea = document.createElement("textarea")
  textarea.value = text
  textarea.setAttribute("readonly", "")
  textarea.style.position = "fixed"
  textarea.style.opacity = "0"
  document.body.appendChild(textarea)
  textarea.select()
  document.execCommand("copy")
  document.body.removeChild(textarea)
}

export function formatSeconds(milliseconds: number) {
  return `${(milliseconds / 1000).toFixed(1)}s`
}

export function buildReport(data: DiagnoseResponse) {
  const fallback = (label: string): EngineResult => ({
    ranked: false,
    position: null,
    mention: null,
    fullResponse: `${label} was not included in the API response.`,
    error: true,
  })

  const engines = [
    ["OpenAI", data.results.gpt4 ?? fallback("OpenAI")],
    ["Claude", data.results.claude ?? fallback("Claude")],
    ["Gemini", data.results.gemini ?? fallback("Gemini")],
  ] as const

  const engineLines = engines
    .map(([label, result]) => {
      const status = result.ranked ? `Ranked #${result.position}` : "Not Ranked"
      return `${label}:  ${status}\nMention: ${result.mention ?? "-"}`
    })
    .join("\n\n")

  return [
    "─────────────────────────────────────",
    "AEO DIAGNOSTIC REPORT",
    "─────────────────────────────────────",
    `Query:   ${data.query}`,
    `Brand:   ${data.targetBrand}`,
    `Result:  ${data.overallScore}`,
    "",
    engineLines,
    "─────────────────────────────────────",
    "Generated by AEO Diagnostic",
    "─────────────────────────────────────",
  ].join("\n")
}
